# Generated by Django 4.2.2 on 2025-09-17 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("astro", "0002_profilecharts"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("today_for_you", models.TextField()),
                ("career_money", models.TextField()),
                ("relationships_love", models.TextField()),
                ("health_energy", models.TextField()),
                ("spiritual", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
