# Generated by Django 4.2.2 on 2025-09-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astro", "0003_homepage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="career_money",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="health_energy",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="relationships_love",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="spiritual",
            field=models.JSONField(),
        ),
    ]
