# Generated by Django 4.2.2 on 2025-09-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astro", "0004_alter_homepage_career_money_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("system_message", models.TextField()),
                ("user_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
